### ISSUE TITLE
Posting notifications

### ISSUE THREAD

**Issue by f2prateek** [Wootric/segment-wootric-ios#1]
Could you clarify a use case for this feature in the Readme?

``` obj-c
[[NSNotificationCenter defaultCenter] addObserver:<OBSERVER> selector:<SELECTOR> name:@"com.wootric.integration.ready" object:<OBJECT>];
```

Segment's SDK actually posts a notification as well when the integration is initialized - https://github.com/segmentio/analytics-ios/blob/master/Pod/Classes/SEGAnalytics.m#L361; so was curious what would be advantage of use the wootric one directly.

**Comment by pJes2** [comment]
ah indeed there is a notification with integration name - missed that one, therefore I'll remove mine as it is not needed
