### ISSUE TITLE
Update WootricSDK to latest version (0.10.0)

### ISSUE THREAD

**Issue by kobusb** [Wootric/segment-wootric-ios#11]
Currently, this pod depends on WootricSDK 0.9.0. Would love to be able to use the latest WootricSDK version, that's currently 0.10.0. This will give us access to the `appear` events (willAppear, didAppear, willDisappear, didDisappear).

Getting the following errors when running `pod update`: 

``` 
[!] Unable to satisfy the following requirements:

- `WootricSDK (= 0.10.0)` required by `Podfile`
- `WootricSDK (~> 0.9.0)` required by `Segment-Wootric (0.2.0)`
```

Thanks in advance! 🙌

**Comment by kobusb** [comment]
@diegoserranoa any chance of getting this updated?

**Comment by diegoserranoa** [comment]
Sure @kobusb! Sorry for the late response. It's been crazy over here. I'll work on the update today, get it reviewed an let you know once this is released!

**Comment by diegoserranoa** [comment]
Updated version... closing issue.
