### ISSUE TITLE
Update Segment to the latest version

### ISSUE THREAD

**Issue by kobusb** [Wootric/segment-wootric-ios#8]
The Segment-Wootric podspec requires Segment 3.5.0, but version 3.6 has been out for a while

This makes it impossible to use Segment-Wootric without downgrading our version of Segment. 

We get the following errors when trying to install SegmentWootric.
```
[!] Unable to satisfy the following requirements:

- `Analytics (~> 3.6)` required by `Podfile`
- `Analytics (~> 3.5.0)` required by `Segment-Wootric (0.1.6)`
```

Relevant lines from our Podfile:
```
pod 'Analytics', '~> 3.6'
pod 'WootricSDK', '0.6.3'
pod 'Segment-Wootric', '0.1.6'
```

**Comment by diegoserranoa** [comment]
Hi @kobusb. Thanks for reporting this. We will update the library as soon as we can.

**Comment by diegoserranoa** [comment]
Hi @kobusb! We've updated the library and there's a new version [0.1.7](https://cocoapods.org/?q=segment-wootric) with the changes.

Thanks for your patience,
Cheers!

**Comment by kobusb** [comment]
Great, thanks for the update! 🙌
